# Site settings
title: Random Projections
header-img: img/escher.jpg
email: tjtorres@ucsc.edu
description: "This blog details my data science and data visualization projects and thoughts."
baseurl: ""
url: "localhost:4000"
github_username:  tjtorres


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#kramdown specs
kramdown:
  input: GFM
  syntax_highlighter: pygments
